const DietPlan = require("../models/DietPlan");
const { generateDietPlan } = require("../services/GeminiService");

const DISCLAIMER =
  "This diet plan is generated by AI for general wellness and informational purposes only. " +
  "It is not a substitute for professional medical or dietary advice. Please consult a registered " +
  "dietitian or doctor before making any major changes to your diet, especially if you have any " +
  "medical condition, allergy, or are pregnant/nursing.";

const generatePlan = async (req, res) => {
  try {
    const { age, weight, height, goal, dietType } = req.body;

    // basic validation
    if (!age || !weight || !height || !goal || !dietType) {
      return res.status(400).json({
        success: false,
        message: "All fields (age, weight, height, goal, dietType) are required.",
      });
    }

    if (age <= 0 || weight <= 0 || height <= 0) {
      return res.status(400).json({
        success: false,
        message: "Age, weight, and height must be positive numbers.",
      });
    }

    const validGoals = ["weight_loss", "weight_gain", "muscle_gain", "maintain"];
    if (!validGoals.includes(goal)) {
      return res.status(400).json({ success: false, message: "Invalid goal value." });
    }

    if (!["veg", "non-veg"].includes(dietType)) {
      return res.status(400).json({ success: false, message: "Invalid dietType value." });
    }

    const plan = await generateDietPlan({ age, weight, height, goal, dietType });

    // save to DB (optional history/analytics) - won't block response if it fails
    try {
      await DietPlan.create({
        age,
        weight,
        height,
        goal,
        dietType,
        plan,
        disclaimer: DISCLAIMER,
      });
    } catch (dbErr) {
      console.error("Could not save diet plan to DB:", dbErr.message);
    }

    return res.status(200).json({
      success: true,
      data: plan,
      disclaimer: DISCLAIMER,
    });
  } catch (error) {
    console.error("generatePlan error:", error.message);
    return res.status(500).json({
      success: false,
      message: "Failed to generate diet plan. Please try again later.",
    });
  }
};

module.exports = { generatePlan };